### ISSUE TITLE
lack of env causes build error

### ISSUE THREAD

**Issue by XahidEx** [theodorusclarence/theodorusclarence.com#265]
![Screenshot_20220122-125359_Brave](https://user-images.githubusercontent.com/88249321/150628467-dede0b2b-d2fb-4fa9-ac75-e35d9aa2df80.jpg)

**Comment by theodorusclarence** [comment]
I’m pretty sure that’s because of the insufficient envs.
I’ll update the .env.example with the newest one later

**Comment by XahidEx** [comment]
I loved this so much. Please try to fix it soon. It's really so amazing 🙈💗

**Comment by XahidEx** [comment]
Failed 😅

**Comment by XahidEx** [comment]
Still 🙈

**Comment by theodorusclarence** [comment]
Yep, that’s the cypress being flaky, the deployment is all good
