### ISSUE TITLE
[BUG] Duplicate project image in side-projects page

### ISSUE THREAD

**Issue by vikasganiga05** [theodorusclarence/theodorusclarence.com#291]
**Describe the bug**
The project [Enigmatics Finder](https://theodorusclarence.com/projects/side-projects#enigmatics-finder) you displayed on the side-projects page is using the same screenshot image of [WhatsApp Helper](https://theodorusclarence.com/projects/side-projects#whatsapp-helper).

**To Reproduce**
1. Go to https://theodorusclarence.com/projects/side-projects#enigmatics-finder
1. It's using [WhatsApp Helper](https://theodorusclarence.com/projects/side-projects#enigmatics-finder) project's screenshot image.

**Screenshots**
> See both project's screenshot image are same :point_down: 

<p float="center">
  <img src="https://user-images.githubusercontent.com/74750414/164294815-bf7e923a-31f4-4daa-a2ec-91d520c94cae.png" width="45%" alt="WhatsApp Helper" />
  &nbsp; &nbsp; &nbsp; &nbsp;
  <img src="https://user-images.githubusercontent.com/74750414/164294909-4a0f2938-7bec-4a68-9564-dc6b7bc572ac.png" width="45%" alt="Enigmatics Finder" />
</p>

**Expected behavior**
Update the [Enigmatics Finder](https://theodorusclarence.com/projects/side-projects#enigmatics-finder) screenshot image to like below one :point_down: 

![image](https://user-images.githubusercontent.com/74750414/164299111-5b5325d9-22b5-4b14-9362-9b6f2d903a7f.png)

**Comment by theodorusclarence** [comment]
This is super helpful, thank you so much!

**Comment by vikasganiga05** [comment]
Most welcome :slightly_smiling_face:
