### ISSUE TITLE
[BUG] Broken link to Enigmatics Finder project

### ISSUE THREAD

**Issue by vikasganiga05** [theodorusclarence/theodorusclarence.com#292]
**Describe the bug**
The link provided under [Enigmatics Finder](https://theodorusclarence.com/projects/side-projects#enigmatics-finder) project on the side-projects page is broken.

**Screenshots**

![Broken Link Screenshot](https://user-images.githubusercontent.com/74750414/164303099-90cef9be-343f-4084-9d13-9163ed46fcd5.png)

**Expected behavior**
Make one of the below changes In [Line 83](https://github.com/theodorusclarence/theodorusclarence.com/blame/b499a75a30fff05ce32c05f5844f4942e61ad948/src/contents/projects/side-projects.mdx#L83) on `src/contents/projects/side-projects.mdx`

> Option 1: Update the link from `https://https//nrp.theodorusclarence.com` to `https://nrp.theodorusclarence.com`
```diff
- [https://nrp.theodorusclarence.com](https://https://nrp.theodorusclarence.com)
+ [https://nrp.theodorusclarence.com](https://nrp.theodorusclarence.com)
```

> Option 2: Update the link from `https://https//nrp.theodorusclarence.com` to `https://nrp.thcl.dev`
```diff
- [https://nrp.theodorusclarence.com](https://https://nrp.theodorusclarence.com)
+ [https://nrp.theodorusclarence.com](https://nrp.thcl.dev)
```

**Comment by theodorusclarence** [comment]
This is super helpful, thank you so much!

**Comment by vikasganiga05** [comment]
> This is super helpful, thank you so much!

It's my pleasure :pray:
