### ISSUE TITLE
i am getting this error while npm run build 

### ISSUE THREAD

**Issue by aanavp** [theodorusclarence/theodorusclarence.com#327]
./src/components/content/CustomCode.tsx
9:14  Error: Unknown property 'jsx' found  react/no-unknown-property

./src/components/images/CloudinaryImg.tsx
92:16  Error: Unknown property 'jsx' found  react/no-unknown-property

./src/pages/_document.tsx
1:1  Error: next/document should not be imported outside of pages/_document.js. See https://nextjs.org/docs/messages/no-document-import-in-page.  @next/next/no-document-import-in-page        

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
info  - Linting and checking validity of types

**Comment by theodorusclarence** [comment]
never got this before, but it looks like a ESLint problem, it registered the files as JS, not TypeScript

**Comment by aanavp** [comment]
can you please help me to setup database to your repo , i made a postgresql database on supabase now i am not able to connect it to code, please help me
