### ISSUE TITLE
need help in setting up database

### ISSUE THREAD

**Issue by aanavp** [theodorusclarence/theodorusclarence.com#328]
can you please help me to setup database to your repo , i made a postgresql database on supabase now i am not able to connect it to code, please help me,your project is very much awesome i want to work on it in my way, i am currently learning front end to not much idea about backend

**Comment by theodorusclarence** [comment]
Hi, you can refer to this tutorial https://supabase.com/docs/guides/integrations/prisma to connect supabase with prisma. 
After you run the migrations, it should work correctly.
