### ISSUE TITLE
when theme changes to dark or light comments reloads

### ISSUE THREAD

**Issue by Chandraprakash-Darji** [theodorusclarence/theodorusclarence.com#329]
I don't have more to say. When I click on button to change theme comments reloads on blog page

**Comment by theodorusclarence** [comment]
Hi, thanks for creating an issue.

Yeah, this is known behaviour. AFAIK, the giscus component doesn't support theme changing without re-rendering the component. If you maybe have any source for that issue, do let me know 😄
