### ISSUE TITLE
How you are styling the mdx content?

### ISSUE THREAD

**Issue by Chandraprakash-Darji** [theodorusclarence/theodorusclarence.com#346]
I am trying to implement but this is the output
![image](https://user-images.githubusercontent.com/93640141/213687135-c92cf5ad-ed9a-43f4-8989-332f066cff75.png)

I also added the this css file of yours but still

```
import '@/styles/dracula.css';
import '@/styles/globals.css';
import '@/styles/mdx.css';
```

**Comment by theodorusclarence** [comment]
![image](https://user-images.githubusercontent.com/55318172/213687983-1163d4cc-774d-4b5a-969d-c891266e9be0.png)

some of the styles in mdx.css are added to `.prose.mdx`

make sure to add class mdx and prose to the article
![image](https://user-images.githubusercontent.com/55318172/213688272-5f9b5e7a-259f-465b-ac3d-b876f68a6b7e.png)

**Comment by Chandraprakash-Darji** [comment]
Both checks is done
```html
  <article className='mdx prose mt-4 transition-colors'>
                <Component />
   </article>
```

Does giving a component to prop is necessary?

**Comment by theodorusclarence** [comment]
if you don't use any, I don't think so.

just to be clear, which style are you trying to achieve?

**Comment by Chandraprakash-Darji** [comment]
Your site:
![image](https://user-images.githubusercontent.com/93640141/213690999-7dd270ae-aa42-4772-87d5-3d8da04c8022.png)
My site:
![image](https://user-images.githubusercontent.com/93640141/213691059-f9adc282-6a5c-4c81-a207-dafd11ad89d8.png)

Content Is copied
- added all css
```
import '@/styles/dracula.css';
import '@/styles/globals.css';
import '@/styles/mdx.css';
import '@/styles/nprogress.css';
```
- Packages I have added: 
```
    "@types/nprogress": "^0.2.0",
    "clsx": "^1.2.1",
    "date-fns": "^2.29.3",
    "esbuild": "^0.17.3",
    "gray-matter": "^4.0.3",
    "mdx-bundler": "^9.2.1",
    "next": "^13.1.1",
    "nprogress": "^0.2.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-icons": "^4.7.1",
    "reading-time": "^1.5.0",
    "rehype-autolink-headings": "^6.1.1",
    "rehype-prism-plus": "^1.5.0",
    "rehype-slug": "^5.1.0",
    "remark-gfm": "^3.0.1",
    "tailwind-merge": "^1.8.1"
```


Any other thing I am mising?

**Comment by theodorusclarence** [comment]
have you add `@tailwindcss/typography` yet?

**Comment by Chandraprakash-Darji** [comment]
No?

**Comment by Chandraprakash-Darji** [comment]
@theodorusclarence Thanks a lot for the help 
![image](https://user-images.githubusercontent.com/93640141/213692660-21e325e1-e039-4386-ac34-cf03b8083cec.png)
