### ISSUE TITLE
Help with deploying;)

### ISSUE THREAD

**Issue by sherryuser** [theodorusclarence/theodorusclarence.com#392]
Hey, I was trying to deploy website to Vercel, but I got this build output with error, could you please help me with that?
<img width="1235" alt="Screenshot 2023-12-23 at 23 19 41" src="https://github.com/theodorusclarence/theodorusclarence.com/assets/72977488/a2b40bf3-6da6-49d4-aa64-b7b8b9cbff7b">

**Comment by theodorusclarence** [comment]
There’s some env missing, try adding the environmet variables to vercel

**Comment by sherryuser** [comment]
Appreciate it, thanks;)
