### ISSUE TITLE
Nice website TC, I was just wondering how do your get your cloudinary images to be displayed in this website..I have tried so many times but cannot find any way..did you an api ?

### ISSUE THREAD

**Issue by theodorusclarence** [theodorusclarence/theodorusclarence.com#398]
Nice website TC, I was just wondering how do your get your cloudinary images to be displayed in this website..I have tried so many times but cannot find any way..did you an api ?

_Originally posted by @MedX101 in https://github.com/theodorusclarence/theodorusclarence.com/discussions/199#discussioncomment-8363388_

**Comment by theodorusclarence** [comment]
If you're using my component, have you tried updating the cloudName?

https://github.com/theodorusclarence/theodorusclarence.com/blob/11186c266ce0862f0b38637d494a86c2632db80d/src/components/images/CloudinaryImg.tsx#L41-L64

One last thing to check to add cloudinary's [domain](https://nextjs.org/docs/app/api-reference/components/image#domains) in next config

**Comment by MedX101** [comment]
I am using your component..  

I don't know which url do you use for banner images..(Where do you get or copy that url)

Like this :

![Screenshot (46)](https://github.com/theodorusclarence/theodorusclarence.com/assets/115746058/793222d8-e7cd-4823-be36-652bc097c2a8)

This is how I have configured  const  link url : 

![Screenshot (49)](https://github.com/theodorusclarence/theodorusclarence.com/assets/115746058/c5a6e099-b46e-4605-822b-c34f6b77742c)


And my cloudinary could name is infosnapzimages as displayed below.

![Screenshot (50)](https://github.com/theodorusclarence/theodorusclarence.com/assets/115746058/3685fb6d-e7f2-44c8-a76c-bbc368de3e1a)


I have been trying to get around this for three days now..I'm really stuck..any help will be appreciated theo..

**Comment by theodorusclarence** [comment]
try opening banner link with the banner value that you pass from mdx

if it don’t open up the image, that means you have the wrong url

**Comment by MedX101** [comment]
How do you get this type of banner url  you used here:  

![302618999-793222d8-e7cd-4823-be36-652bc097c2a8](https://github.com/theodorusclarence/theodorusclarence.com/assets/115746058/b36770ff-9094-463f-9b86-53f3b34ccb44)


Pls bear with me, I'm beginner learn web development.

**Comment by theodorusclarence** [comment]
copy the image link in cloudinary, then get the name of the file from the end of link

**Comment by MedX101** [comment]
thanks for all the replies theo..   this is  the only link i get :   

https://res.cloudinary.com/infosnapzimages/image/upload/v1707215266/banner/photo-1707080181888-25efd661305e_wb53rx.jpg

but as you said i should only copy this  "photo-1707080181888-25efd661305e_wb53rx.jpg"  

but what i have noticed is that, there is this path  "v1707215266" which  might be causing an issue., and i have noticed that in all  your banner links theres no ".jpg "

**Comment by theodorusclarence** [comment]
I'm pretty sure you can now change the `BANNER_LINK` to 
```jsx
const BANNER_LINK = `https://res.cloudinary.com/infosnapzimages/image/upload/f_auto,g_auto,c_fill,ar_4:5,w_1200/v1707215266/banner/${...}`
```

**Comment by MedX101** [comment]
"v1707215266" it keeps on changing on each picture.i dont know  if this is cloudinary upgrade or what.. the values/path keeps on changing..

**Comment by theodorusclarence** [comment]
Oh, i tried removing the v170... and it's still routes to the correct picture

https://res.cloudinary.com/infosnapzimages/image/upload/banner/photo-1707080181888-25efd661305e_wb53rx.jpg

you can completely remove the v... then

```jsx
const BANNER_LINK = `https://res.cloudinary.com/infosnapzimages/image/upload/f_auto,g_auto,c_fill,ar_4:5,w_1200/banner/${...}`
```


> and i have noticed that in all your banner links theres no ".jpg " 

as for the `.jpg` you can interchangebly use or not use them, your preference. You can even directly convert to `.png` or `.webp` depending on what you need
